### ISSUE TITLE
Error 32: Could not authenticate you

### ISSUE THREAD

**Issue by MasinAD** [julianlam/nodebb-plugin-sso-twitter#17]
```
23/9 21:55 [22892] - error: /auth/twitter
 Error: {"errors":[{"code":32,"message":"Could not authenticate you."}]}
    at Strategy.parseErrorResponse (/srv/de/larp-bb/nodebb/node_modules/nodebb-plugin-sso-twitter/node_modules/passport-twitter/lib/strategy.js:182:10)
    at Strategy.OAuthStrategy._createOAuthError (/srv/de/larp-bb/nodebb/node_modules/nodebb-plugin-sso-twitter/node_modules/passport-twitter/node_modules/passport-oauth1/lib/strategy.js:349:16)
    at /srv/de/larp-bb/nodebb/node_modules/nodebb-plugin-sso-twitter/node_modules/passport-twitter/node_modules/passport-oauth1/lib/strategy.js:218:41
    at /srv/de/larp-bb/nodebb/node_modules/nodebb-plugin-sso-twitter/node_modules/passport-twitter/node_modules/passport-oauth1/node_modules/oauth/lib/oauth.js:543:17
    at passBackControl (/srv/de/larp-bb/nodebb/node_modules/nodebb-plugin-sso-twitter/node_modules/passport-twitter/node_modules/passport-oauth1/node_modules/oauth/lib/oauth.js:397:13)
    at IncomingMessage.<anonymous> (/srv/de/larp-bb/nodebb/node_modules/nodebb-plugin-sso-twitter/node_modules/passport-twitter/node_modules/passport-oauth1/node_modules/oauth/lib/oauth.js:409:9)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickDomainCallback (node.js:459:13)
```

Seems like a duplicate of #12. If I can provide you with any other information that might help you, jus ask.

**Comment by Jdesk** [comment]
fyi i'm working on this - i just have 10 million projects - i know this might be kinda old but it's current.  don't wanna put it out there - i switched over to debian - actually real simple - meaning v9.x - gh is just a playground for me - all this crap is getting nuts - too many gd integrations - os has become alll $$$$$$$$.

**Comment by Jdesk** [comment]
but i'll give them all this - our repos - our stuff - their space. no cash - can just keep using tried and true apps that just get better - eg. travis.  it's the os that's getting bad.

**Comment by Jdesk** [comment]
we all know it's the cb - the initial auth works fine - fb works fine - but i have the sdk and all sorts of rum analytics.  tried and true :+1:

**Comment by Jdesk** [comment]
gh works as well - i think haven't tried it lately.

**Comment by GeARCraft1** [comment]
Same problem

**Comment by armsofter** [comment]
Same problem and cant find any solution.

**Comment by julianlam** [comment]
Still unable to reproduce as per #12. Can you try regenerating your API key and secret, and ensuring that "Sign in via Twitter" is enabled?

**Comment by hsntgm** [comment]
@armsofter @GabrielTK 
Did you check space?

Because while you copy/paste your Consumer Key (API Key) and Consumer Secret (API Secret) to nodebb plugin field from twitter app page always there is a 1 line gap (space) at the beginning of the your code also check at the end of the code.

Simply fill the blanks areas:)
Plugin is working.

Best Regards.

**Comment by barisusakli** [comment]
fwiw this happens on community.nodebb.org as well.

Clicking 

![image](https://github.com/julianlam/nodebb-plugin-sso-twitter/assets/2583394/a3ba34dd-4cb9-46b1-9364-dad12e0fcc1d)

results in

![image](https://github.com/julianlam/nodebb-plugin-sso-twitter/assets/2583394/e333e943-e776-4269-8b3d-af02edc570ef)

**Comment by julianlam** [comment]
Ah, perhaps this is related to Twitter API being paid service? 😆 SSO dead?
