### ISSUE TITLE
Desktop applications only support the oauth_callback value 'oob'

### ISSUE THREAD

**Issue by a5mith** [julianlam/nodebb-plugin-sso-twitter#7]
Had the log open when doing something else, and this was in there along with some other things... 

    Error: Desktop applications only support the oauth_callback value 'oob'
    at Strategy.parseErrorResponse (/home/a_5mith/35hz/node_modules/nodebb-plugin-sso-twitter/node_modules/passport-twitter/lib/strategy.js:178:10)
    at Strategy.OAuthStrategy._createOAuthError (/home/a_5mith/35hz/node_modules/nodebb-plugin-sso-twitter/node_modules/passport-twitter/node_modules/passport-oauth1/lib/strategy.js:349:16)
    at /home/a_5mith/35hz/node_modules/nodebb-plugin-sso-twitter/node_modules/passport-twitter/node_modules/passport-oauth1/lib/strategy.js:218:41
    at /home/a_5mith/35hz/node_modules/nodebb-plugin-sso-twitter/node_modules/passport-twitter/node_modules/passport-oauth1/node_modules/oauth/lib/oauth.js:543:17
    at passBackControl (/home/a_5mith/35hz/node_modules/nodebb-plugin-sso-twitter/node_modules/passport-twitter/node_modules/passport-oauth1/node_modules/oauth/lib/oauth.js:397:13)
    at IncomingMessage.<anonymous> (/home/a_5mith/35hz/node_modules/nodebb-plugin-sso-twitter/node_modules/passport-twitter/node_modules/passport-oauth1/node_modules/oauth/lib/oauth.js:409:9)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at process._tickDomainCallback (node.js:463:13)

**Comment by mashihua** [comment]
Go to Twitter's app setting at Callback URL field entry following:
http://example.com/auth/twitter/callback
